package org.geecon.demo.application.admin.contact;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContactViewDesign extends HorizontalSplitPanel {
    protected TextField filterField;
    protected Button addButton;
    protected Grid<org.geecon.demo.domain.contact.dto.ContactQueryDto> grid;
    protected TextField nameField;
    protected TextField companyField;
    protected TextArea descriptionField;
    protected TextField addressField;
    protected TextField cityField;
    protected TextField zipCodeField;
    protected TextField phoneField;
    protected TextField emailField;
    protected Button editButton;
    protected Button saveButton;
    protected Button discardButton;

    public ContactViewDesign() {
        Design.read(this);
    }
}
